"""Export audit reports as Markdown or PDF."""

import json

from app.models.audit import Audit


def export_audit_markdown(audit: Audit) -> str:
    report = audit.report_json or {}
    vulns = report.get("vulnerabilities", [])
    gas_opts = report.get("gas_optimizations", [])
    practices = report.get("best_practices", [])

    lines = [
        f"# Security Audit Report: {audit.contract_name or 'Contract.sol'}",
        "",
        f"**Date:** {audit.completed_at or audit.created_at}",
        f"**AI Model:** {audit.ai_model_used}",
        f"**Processing Time:** {audit.processing_ms}ms" if audit.processing_ms else "",
        f"**Overall Risk:** {audit.overall_risk or 'N/A'}",
        f"**Security Score:** {report.get('risk_score', 'N/A')}/100",
        "",
        "## Executive Summary",
        "",
        report.get("executive_summary", "No executive summary available."),
        "",
        "## Vulnerability Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| Critical | {audit.critical_count} |",
        f"| High     | {audit.high_count} |",
        f"| Medium   | {audit.medium_count} |",
        f"| Low      | {audit.low_count} |",
        f"| Info     | {audit.info_count} |",
        "",
        "## Vulnerabilities",
        "",
    ]

    for v in vulns:
        lines.extend(
            [
                f"### {v.get('id', 'V?')}: {v.get('title', 'Untitled')}",
                "",
                f"- **Severity:** {v.get('severity', 'N/A')}",
                f"- **Description:** {v.get('description', '')}",
            ]
        )
        if v.get("line_hint"):
            lines.append(f"- **Location:** {v['line_hint']}")
        lines.extend(
            [
                f"- **Recommendation:** {v.get('recommendation', '')}",
                "",
            ]
        )
        if v.get("code_fix"):
            lines.extend(
                [
                    "```solidity",
                    v["code_fix"],
                    "```",
                    "",
                ]
            )

    if gas_opts:
        lines.extend(
            [
                "## Gas Optimizations",
                "",
            ]
        )
        for g in gas_opts:
            lines.extend(
                [
                    f"- **{g.get('title', '')}:** {g.get('description', '')}",
                    f"  - *Recommendation:* {g.get('recommendation', '')}",
                    "",
                ]
            )

    if practices:
        lines.extend(
            [
                "## Best Practices",
                "",
            ]
        )
        for bp in practices:
            lines.append(f"- {bp}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by Nexus AI Smart Contract Auditor*")

    return "\n".join(lines)


def export_audit_json(audit: Audit) -> str:
    report = audit.report_json or {}
    return json.dumps(
        {
            "contract_name": audit.contract_name,
            "overall_risk": audit.overall_risk,
            "risk_score": report.get("risk_score"),
            "vulnerabilities": report.get("vulnerabilities", []),
            "gas_optimizations": report.get("gas_optimizations", []),
            "best_practices": report.get("best_practices", []),
            "executive_summary": report.get("executive_summary", ""),
            "ai_model_used": audit.ai_model_used,
            "processing_ms": audit.processing_ms,
            "completed_at": str(audit.completed_at),
        },
        indent=2,
    )
